import { Inter } from "next/font/google";
import "./globals.css";
import { BankCounterContextProvider } from "@/context/bank_counter_context";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Axi Frontend Task",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <BankCounterContextProvider>
        <body className={inter.className}>{children}</body>
      </BankCounterContextProvider>
    </html>
  );
}
